# db settings

# setup postgresql cluster
    pg_lsclusters
    sudo pg_createcluster 14 cluster_name --port 5433

# /etc/postgresql/14/cluster_name/postgresql.conf
    listen_addresses = '*'
    listen_addresses = 'localhost,172.25.157.55,205.175.118.*'
    max_connections = 400  # (change requires restart)
    port = 5433
    ssl = on

# /etc/postgresql/14/cluster_name/pg_hba.conf
# in pg_hba.conf allow only your campus/server subnet, not 0.0.0.0/0
    # INFO 330 Course
    host    all     all     172.25.0.0/16     scram-sha-256
    host    all     all     10.102.0.0/16     scram-sha-256

# restart and login
    sudo pg_ctlcluster 14 cluster_name restart
    psql -h 127.0.0.1 -p 5433 -U postgres
